AstrBotDevs/AstrBot

- util/t2i/renderer.py
- util/t2i/strategies/base_strategy.py
- util/t2i/strategies/local_strategy.py
- util/t2i/strategies/network_strategy.py
实现了 #176
实现自定义文转图，更高的插件自由度。
修改了 util/t2i 包。
AstrBot 使用 HTML + Jinja2 的方式来渲染文转图模板。
比如你可以自定义一个 HTML 模板：
```html
<h1 style="color: red">{{title}}</h1>
<p>{{content}}</p>
```
然后传递一个字典：
```py
{
"title": "警报!",
"content": "10 分钟后课程大作业截止！"
}
```
这样，AstrBot 就会按照这个 HTML 模板生成一张图片，图片内容为 `警报!` 和 `10 分钟后课程大作业截止！`。 
```py
TMPL = '''
<div style="font-size: 32px;"> 
<h1 style="color: red">{{title}}</h1>
<p>{{content}}</p>
</div>
'''
from util.plugin_dev.api.v1.bot import Context, AstrMessageEvent, CommandResult
from util.plugin_dev.api.v1.config import *
class HelloWorldPlugin:
"""
AstrBot 会传递 context 给插件。
- context.register_commands: 注册指令
- context.register_task: 注册任务
- context.message_handler: 消息处理器(平台类插件用)
"""
def __init__(self, context: Context) -> None:
self.context = context …
```
> 自定义文转图 HTML 模板

- .gitignore
- astrbot/core/config/default.py
- astrbot/core/provider/func_tool_manager.py
- astrbot/core/provider/manager.py
- astrbot/core/provider/sources/anthropic_source.py
- requirements.txt
https://github.com/Soulter/AstrBot/issues/558
Anthropic Claude的API与OpenAI的不兼容，希望增加对Claude的支持
在`.gitignore`中添加了`.conda`文件夹，对使用conda环境的用户更加友好
在`requirements.txt`添加了anthropic库
添加了`anthropic_source.py`，用以处理Anthropic API（**警告**：尚未对上传图片进行测试，可能这部分存在bug）
在`func_tool_manager.py`文件中增加了`get_func_desc_anthropic_style()`函数，以处理Anthropic的函数调用API。
在`default.py`中添加claude模板
在前端面板的“服务提供商配置”上添加`anthropic_chat_completion`类型
前端面板将“服务提供商配置”中的“文本生成模型”里“模型最大输出长度(tokens) (max_tokens)”对于`anthropic_chat_completion`类型改为常驻或显式的，因为调用Anthropic API，`max_tokens`是必须的
> 添加对Anthropic Claude API的支持

- astrbot/core/platform/sources/webchat/webchat_event.py
webchat未处理base64，导致Image.fromBytes在webchat平台中出现问题
增加base64处理逻辑
> 🐛 fix: 修复webchat未处理base64的问题

- astrbot/core/platform/sources/aiocqhttp/aiocqhttp_platform_adapter.py
修复了 #586
这里的切片会报KeyError导致判断没办法进行下去
获取文件失败会导致传入未预期的参数file_id
修改切片为`get`方法
将`a = ComponentTypes[t](**m['data'])`和`abm.message.append(a)`的调用移到了各个具体的分支内，然后添加了`else`分支处理其他类型的消息
> 🐛fix: 修复aiocqhttp_platform_adapter文件相关判断逻辑

- astrbot/core/platform/sources/telegram/tg_event.py
修复了 #613
telegram适配器中未处理base64，导致Image.fromBytes在telegram平台中出现问题
将base64转为bytes后发送
> 🐛 fix: 修复telegram适配器中未处理base64的问题

- astrbot/core/platform/sources/aiocqhttp/aiocqhttp_platform_adapter.py
修复了 #621
OneBot V11 通知类事件某些情况会无法回复问题
astrbot/core/platform/sources/aiocqhttp/aiocqhttp_platform_adapter.py 中：
async def convert_handle_notice_event(self, event: Event) -> AstrBotMessage:
出错行：abm.session_id = abm.sender.user_id + "" + str(event.group_id)
将出错行改为abm.session_id = str(abm.sender.user_id) + "_" + str(event.group_id)
> fix bug #621

- astrbot/core/pipeline/whitelist_check/stage.py
- astrbot/core/platform/sources/gewechat/client.py
- packages/astrbot/main.py
修复了 #765 #398
解决已记录gewechat的appid失效设备不存在的情况下，astrbot无法再次登陆个人微信的bug
修复完善astrbot/core/platform/sources/gewechat/client.py的相关登陆代码逻辑：
效果如下：
实测：
第二次登陆：
`2025-03-11T00:23:02.813318066+08:00  [00:23:02] [Core] [INFO] [gewechat.client:80]: 获取到 Gewechat Token: abcdefg 
2025-03-11T00:23:02.820156441+08:00  [00:23:02] [Core] [INFO] [gewechat.client:325]: 使用 APPID: wx_xxx, bba 
2025-03-11T00:23:02.832609063+08:00  [00:23:02] [Core] [ERRO] [gewechat.client:338]: 检测到无效的appid: wx_xxx，将清除并重新登录。 
2025-03-11T00:23:03.771755138+08:00  [00:23:03] [Core] [INFO] [gewechat.client:347]: APPID: wx_new_xxx 
2025-03-11T00:23:03.771877377+08:00  [00:23:03] [Core] [WARN] [gewechat.client:348]: 请打开该网址，然后使用微信扫描二维码登录: https://api.cl2wm.cn/api/qrcode/code?text=http://weixin.qq.com/x/wx_xxx `
重启容器： …
> fix: 修复个人微信非第一次登陆情况，已记录gewechat的appid失效设备不存在导致无法重新登陆个人微信的bug

- astrbot/core/platform/sources/gewechat/client.py
修复了 #754
astrbot通过gewchat平台，无论是私聊还是群聊，当用户本人发出去消息时也会被机器人回复消息，这个不应该发生
client.py 设置过滤本人发出的消息即可。
> fix: 修复gewechat平台用户本人发消息触发消息回复的bug

- astrbot/core/platform/sources/qqofficial/qqofficial_message_event.py
这个问题还没有创建相关Issue
使用qq官方机器人适配器时,如果使用了 `Image.fromBytes`  `Image.fromBase64` 来组装包含图片的消息链,**消息会一直无法发出**,原因是适配器在bytes转换成base64后,错误的把base64内容传入`file_to_base64`函数,导致异步线程一直尝试从文件系统中读取不存在的路径,导致异步任务失败
报错信息大致如下:
`i.file`的内容就是url字符串,而`i.file`的头部不为`file:///`和`http`,那就剩下`base64://`了作为协议头部了吧
当协议头部是`base64://`时,直接吧字符串前面的url头部移除就能得到`image_base64`了,而不是这个url放进`file_to_base64`里处理
> 修复了使用Image.fromBytes等包装的图片消息链无法通过qq官方机器人适配器发送的bug

- astrbot/core/pipeline/waking_check/stage.py
修复了 #806 
如题
在`event.stop_event`之前调用`event._post_send`将消息发送到消息平台,在此之前`event.stop_event`之后`event._post_send`未被调用从而导致 #806 的问题
> 修复命令参数报错信息无法发送至qq官方机器人平台的bug

- astrbot/core/platform/sources/telegram/tg_adapter.py
- astrbot/dashboard/routes/stat.py
修复了 #954
无法处理stickers
话题内正常消息被识别为回复消息
添加stickers处理逻辑
排除“回复话题首条消息”的情况
> Telegram适配器消息处理功能增强

- dashboard/src/components/ConfirmDialog.vue
- dashboard/src/components/shared/ExtensionCard.vue
- dashboard/src/main.ts
- dashboard/src/plugins/confirmPlugin.ts
- dashboard/src/views/ExtensionPage.vue
修复了 #917 
添加插件删除操作二次确认，修复了插件列表会没有非空判断 filter报错
添加确认弹框组件，ts封装实现全局调用。
> feat: 删除插件添加二次确认，插件列表添加非空判断

- packages/session_controller/main.py
将对只有一个 @ 的消息内容的处理改成调用llm回复
原本预设好的文案非常生硬，很影响聊天。我认为改成调用llm可以使对只有一个 @ 的消息内容的处理的回复更个性化更生动
我将原本直接发送预设文案改成了通过预设的提示词调用llm，如果调用失败则发送预设的文案
> 将对只有一个 @ 的消息内容的处理改成调用llm回复

- astrbot/core/star/star_manager.py
修复了 #995 
参数格式不正确影响后续判断
使用文件名作为插件名传参
> fix: install_plugin_from_file 方法load传参数改为文件名

- astrbot/core/message/message_event_result.py
- 新增 at 方法，用于添加 At 消息到消息链中
- 新增 at_all 方法，用于添加 AtAll 消息到消息链中
在开发插件时发现使用event.send()发送消息时无法@对方，代码中添加上述方法后测试@能生效，后续我会分享相关插件
await event.send(
MessageChain().at(user_name, user_id).message(f"您今日的AI访问次数已达上限({limit}次)，"
f"请明天再试或联系管理员提升限额。")
)
> feat(core): 在 MessageChain 类中添加 at 和 at_all 方法

- astrbot/core/core_lifecycle.py
- astrbot/core/star/star_manager.py
修复了 #1039 
当通过CTRL+C终止Astrobot时未调用插件的terminate()方法，导致插件资源未能正常释放。
添加调用逻辑
> 在lifecycle新增插件资源清理逻辑

- astrbot/core/provider/manager.py
- packages/astrbot/main.py
修复了 #1055
无对话情况下提示不明确。禁用提供商没有自动切换
提前判断是否存在对话。若禁用提供商，自动切换到另一个可用的提供商。
> perf: 优化无对话情况下设置人格的反馈；若禁用提供商，自动切换到另一个可用的提供商

- astrbot/core/pipeline/respond/stage.py
- astrbot/core/utils/path_util.py
修复了 #1154 
增加了`发送文件`时，也能触发路径映射的功能
参考`preprocess_stage.stage`的实现，在`respond.stage`里执行路径映射检查。
多添加了Window路径支持（基于`os.path.exists`推测切分路径）
> 文件发送时支持路径映射

- astrbot/core/message/components.py
- astrbot/core/pipeline/respond/stage.py
- astrbot/core/platform/sources/lark/lark_event.py
修复了 KimigaiiWuyi/astrbot_plugin_gscore_adapter#2
[现有的逻辑无法在飞书适配器上发送Base64图片](https://github.com/KimigaiiWuyi/astrbot_plugin_gscore_adapter/issues/2)
当图片为base64结构时，将`comp.file`转为bytes进行上传
> 🐛 修复飞书适配器转换消息过程中无法正确转化Base64图片

- astrbot/core/updator.py
解决了 #1460
正常使用astrbot没有问题，python的安装和路径都没有问题，但是在重启的时候会报错，只能使用Ctrl+c强制退出，经过和大佬讨论研究，发现是文件\AstrBot\astrbot\core\updator.py中一个方法对于路径的读取问题，修改后解决
使用subprocess.Popen启动新进程，修复原方案识别路径空格的问题
> Fix issue 1460

- dashboard/src/components/shared/ReadmeDialog.vue
之前readme对话框内文字内容始终渲染为黑色，深色模式下难以看清，
考虑将原本固定的颜色值更改为变量
更改`.markdown-body`系列css样式代码
> fix(readmeDialog): 修复了readme对话框内markdown渲染样式问题

- dashboard/src/components/shared/AstrBotConfig.vue
该提交与 #1919 关联。
精准定位错误 @Pine-Ln，Fix from Gemini 2.5 Pro.
这个问题是由两个错误叠加造成的：
1. **组件崩溃**：`AstrBotConfig.vue` 混用了 Vue 3 的 `<script setup>` 和旧式 `<script>` 写法，导致作用域冲突，模板无法访问国际化函数 `t`，引发 `ReferenceError: t is not defined`。
2. **设置项不显示**：原代码根据用户已保存的设置数据来渲染字段，导致新增的设置项（如 `editor_mode`）因为用户配置中没有初始值而不显示。
1. **统一 API 写法**：将整个组件重构为纯 `<script setup>` 写法，解决作用域冲突。
2. **修正渲染逻辑**：将 `v-for` 循环改为遍历设置蓝图 (metadata) 而不是用户数据，确保所有定义的设置项都能显示。
解决了 #1919
> Fix: 仪表盘的『插件配置』中不显示 JSON 编辑窗

- astrbot/core/provider/func_tool_manager.py
- astrbot/core/provider/manager.py
- astrbot/dashboard/routes/tools.py
- dashboard/src/components/shared/ItemCard.vue
- dashboard/src/i18n/locales/en-US/features/tool-use.json
- dashboard/src/i18n/locales/zh-CN/features/tool-use.json
- dashboard/src/views/ToolUsePage.vue
目前 WebUI 上添加 / 关闭 MCP Server 时是立即返回的，导致没办法关注其添加时返回的结果，带来困惑
大量使用 asyncio 的 Event 和 Future 特性来重构了 MCP Server 的载入和终止机制，这样的效果是前端将会有一个 loading 来等待逻辑执行完毕。
然而，在我的测试当中发现，在尝试加载 MCP Server 提供商（如 Smithery）的错误配置的 MCP Server 时，报错没有被抛出，导致一直会卡在  `await self.session.initialize()` 当中。我给的暂时的处理办法时加一个 timeout（默认是 20s），当超时时，会抛出异常，然而这种方式没办法捕获并且记录被错误配置的 MCP Server 的异常信息，并且由于 astrbot 的 logger 没有捕获到，也会导致 WebUI 的控制台观察不到错误，需要通过终端查看。这是一个值得优化的点。
---
附：
当错误配置 MCP Server 的 Streamable HTTP URL 时，Smithery 的报错如下：
```bash
Error in post_writer: Client error '422 Unprocessable Entity' for url 'https://server.smithery.ai/@smithery-ai/github/mcp?api_key=9d3xxxxx-8xxxxxxxd-a840-23xxxxxb0d66&profile=revolutionary-eagle-dxxxxxxxX1'
```
> Refactor: mcp server reload mechanism

- packages/astrbot/main.py
closes: #2821
---
fix: 识别引用消息的图片时优先使用默认图片转述提供商
closes: [#2821](https://github.com/AstrBotDevs/AstrBot/issues/2821)
fix: 识别引用消息的图片时优先使用默认图片转述提供商
closes: [#2821](https://github.com/AstrBotDevs/AstrBot/issues/2821)
配置使用默认图片转述提供商，然后在 QQ 中引用带有图片的消息
---
> fix: 识别引用消息的图片时优先使用默认图片转述提供商

- astrbot/core/agent/runners/tool_loop_agent_runner.py
fixes: #2940
---
修复 on_tool_end无法获得工具返回的结果的问题。这是由于参数传递错误导致的。
---
> fix: on_tool_end无法获得工具返回的结果
