AstrBotDevs/AstrBot

cores/qqbot/core.py

修复Tokens超限后重新请求无法发送QQ信息的问题 #27

fix: 修复Tokens超限后重新请求无法发送QQ信息的问题 #27

---

cores/qqbot/core.py

fix: 修复人格的一些bug #30 
feat: 自定义人格

fix: 修复人格的一些bug #30

---

cores/qqbot/core.py
launcher.py
model/command/command.py
model/command/command_openai_official.py
model/command/command_rev_chatgpt.py
model/command/command_rev_edgegpt.py
model/provider/provider.py
model/provider/provider_openai_official.py
model/provider/provider_rev_chatgpt.py
model/provider/provider_rev_edgegpt.py
requirements.txt

61 enhancement 重构代码增强稳定性

---

cores/qqbot/core.py
main.py
model/command/command.py
model/provider/provider_rev_chatgpt.py

55 multi models switch

---

astrbot/bootstrap.py
astrbot/message/handler.py
model/command/internal_handler.py
model/command/manager.py
type/command.py
type/message_event.py
type/types.py
util/agent/func_call.py
util/agent/web_searcher.py
util/t2i/strategies/network_strategy.py

- 新增 Provider 注册接口。
- 新增 provider 指令。

feat: 新增 Provider 注册接口；新增 provider 指令

---

.dockerignore
.github/workflows/docker-image.yml
Dockerfile

优化 构建方式
提升 actions 可读性
添加 arm64位镜像

优化 docker build

---

.codecov.yml
.coveragerc
.github/workflows/coverage_test.yml
astrbot/bootstrap.py
astrbot/message/handler.py
model/platform/qq_aiocqhttp.py
model/platform/qq_official.py
model/provider/openai_official.py
tests/mocks/onebot.py
tests/mocks/qq_official.py
tests/test_message.py
type/types.py
util/agent/func_call.py

自动化测试以减少人力开支
- 添加了部分 Mock 数据生成和单测；
- 添加了 workflow 以自动化测试，输出到 Codecov。

[Feature] 添加自动化测试 

---

dashboard/helper.py

修复了 #207
修复 #207
1. 修改了配置递归校验逻辑
2. 增加了对一些配置项类型的强制类型转换尝试

fix: 修复仪表盘保存配置递归校验失效的问题

---

astrbot/core/config/default.py
astrbot/core/provider/entites.py
astrbot/core/provider/func_tool_manager.py
astrbot/core/provider/manager.py
astrbot/core/provider/sources/gemini_source.py

支持通过 Google GenAI 访问 Gemini 模型

---

astrbot/core/config/default.py
astrbot/core/pipeline/result_decorate/stage.py
astrbot/core/platform/manager.py
astrbot/core/platform/sources/gewechat/client.py
astrbot/core/platform/sources/gewechat/gewechat_event.py
astrbot/core/platform/sources/gewechat/gewechat_platform_adapter.py
astrbot/core/star/star_manager.py

初步接入 gewechat 文字交互

---

astrbot/core/provider/func_tool_manager.py

fix: 修复Gemini函数调用时，parameters为空对象导致的错误

---

packages/python_interpreter/main.py

chore: update main.py

---

astrbot/core/conversation_mgr.py
astrbot/core/core_lifecycle.py
astrbot/core/db/__init__.py
astrbot/core/db/po.py
astrbot/core/db/sqlite.py
astrbot/core/db/sqlite_init.sql
astrbot/core/pipeline/process_stage/method/llm_request.py
astrbot/core/provider/entites.py
astrbot/core/provider/manager.py
astrbot/core/provider/provider.py
astrbot/core/provider/sources/gemini_source.py
astrbot/core/provider/sources/llmtuner_source.py
astrbot/core/provider/sources/openai_source.py
astrbot/core/provider/sources/zhipu_source.py
astrbot/core/star/context.py
astrbot/core/utils/param_validation_mixin.py
astrbot/dashboard/routes/chat.py
packages/astrbot/main.py

当前版本的 AstrBot 只能单对话，清除会话时带来不小的损失。
本 PR 实现了更好的对话管理，可以通过 `/ls`, `/switch`, `/del`, `/new` 来管理对话。
对话列表是隔离的，基于 `unified_message_origin` 隔离。
并且实现了人格的隔离，每个对话可以拥有独立的人格设定。

feat: 更好的对话管理

---

astrbot/core/utils/dify_api_client.py

修复了 #298 
调用dify api，返回的response字符串可能是多个`data:`开头的json串。需要分开处理
1. 在DifyAPIClient.chat_messages函数中，处理dify api response返回多个json串的情况。
2. 在DifyAPIClient.workflow_run函数中，处理dify api response返回多个json串的情况。
3. 在DifyAPIClient.workflow_run函数中，抛出异常时，更正了错误消息中的方法名。

fix bug #298

---

astrbot/core/config/default.py
astrbot/core/pipeline/result_decorate/stage.py
astrbot/core/provider/manager.py
astrbot/core/provider/sources/fishaudio_tts_api_source.py
requirements.txt

修复了 #428
* 添加对 [fishaudio tts](https://fish-audio.cn/)的支持
* 新增依赖`ormsgpack`以支持序列化操作

支持 fishaudio tts 文字转语音

---

.gitignore
astrbot/core/config/default.py
astrbot/core/platform/manager.py
astrbot/core/platform/sources/qqofficial/qqofficial_message_event.py
astrbot/core/platform/sources/qqofficial/qqofficial_platform_adapter.py
astrbot/core/platform/sources/qqofficial_webhook/qo_webhook_adapter.py
astrbot/core/platform/sources/qqofficial_webhook/qo_webhook_event.py
astrbot/core/platform/sources/qqofficial_webhook/qo_webhook_server.py
requirements.txt

1. 在 HTTP OpenAPI 部分复用了 botpy 里面的相关实现。
2. 暴露 6196 端口运行回调服务器。

支持 Webhook 方式接入 QQ 官方机器人平台

---

README_ja.md

I created Japanese translated README.

docs: add Japanese README

---

astrbot/core/star/filter/command.py
astrbot/core/star/filter/command_group.py
astrbot/core/star/register/star_handler.py

✨ feat: 添加命令和命令组的别名支持

---

packages/astrbot/main.py

当使用 `/ls 2` 命令查看分页对话列表时，如果当前对话不在当前分页中，qq中抛出convs异常，控制台中抛出 `KeyError` 异常。
分析后我认为是原代码在生成_titles字典时，只遍历了分页后的对话，而不是所有对话，导致当前对话不在当前页时，无法在_titles中找到对应的键。
1. 使用`/new`创建超过6个对话。
2. 输入 `/ls 2`
3. 当前对话 ID 不在第二页的列表中
4. 触发 `KeyError: '1e44d7fa-9e7e-4d79-8fa1-e72269a4717d'`
- 提前生成所有对话的标题字典 `_titles`
- 分页时从全局字典获取标题，而非仅当前页
- 添加页码有效性检查
qqname/qqid: /ls 2 
[00:44:33| ERROR] [star_request.py:40]: Traceback (most recent call last):
File "L:\qq\Qbot\AstrBotLauncher-0.1.5.4\AstrBot\astrbot\core\pipeline\process_stage\method\star_request.py", line 36, in process
async for ret in wrapper:
File "L:\qq\Qbot\AstrBotLauncher-0.1.5.4\AstrBot\astrbot\core\pipeline\stage.py", line 60, in _call_handler
ret = await ready_to_call
^^^^^^^^^^^^^^^^^^^
File "L:\qq\Qbot\AstrBotLauncher-0.1.5.4\AstrBot\packages\astrbot\main.py" …

fix: resolve KeyError when current conversation is not in paginated list

---

README_en.md

docs: add English README
I created English translated README.

docs: add English README

---

astrbot/core/config/default.py
astrbot/core/provider/manager.py
astrbot/core/provider/sources/gsvi_tts_source.py

feat: 添加 GSVI tts 支持 #545 #351

---

packages/astrbot/main.py

修复了 #666 
为switch_conv的index参数添加类型判断
为switch_conv的index参数添加类型判断

为switch_conv的index参数添加类型判断

---

astrbot/core/pipeline/whitelist_check/stage.py
compose.yml
packages/astrbot/main.py

#763 
#744 遗漏更改
- Updated compose.yml to mount system time and timezone
- Included timezone information in system prompt
相关doc更新：https://github.com/Soulter/AstrBot-docs/pull/9

update compose.yml to mount system time and tz

---

astrbot/core/message/components.py

支持嵌套转发，里层包含多条信息

---

astrbot/core/message/components.py

修复无法发送非嵌套的转发消息的问题

---

astrbot/core/platform/sources/gewechat/client.py

wx回调的消息，可能存在一些为处理的逻辑，导致控制台会有一些警告提醒。
做了一些简单的已知消息类型的接收。

微信有未处理的消息类型，导致控制台打印太多的日志

---

.gitignore
astrbot/core/pipeline/process_stage/method/llm_request.py
astrbot/core/platform/sources/qqofficial_webhook/qo_webhook_server.py
astrbot/core/platform/sources/wecom/wecom_adapter.py
astrbot/core/provider/func_tool_manager.py
astrbot/core/star/register/star_handler.py
astrbot/dashboard/server.py

修改注册函数工具时的打印信息

---

dashboard/src/layouts/full/vertical-sidebar/VerticalSidebar.vue

修复了 #XYZ
优化侧边栏悬浮文档iframe的交互与样式
- 添加可拖拽的悬浮iframe，通过全局鼠标事件监听确保拖拽不中断
- 限制iframe窗口的最小尺寸（min-width / min-height），防止窗口缩小至不可用状态
- 在iframe右上角新增关闭按钮，并调整样式为带有圆角的方框
- 扩大拖拽区域至整个header，优化拖拽体验，同时在拖拽过程中禁用文字选中
- 更新版本信息和面板更新提示的显示逻辑

🎈 perf: 优化iframe窗口，加入了关闭按钮

---

dashboard/src/layouts/full/vertical-sidebar/VerticalSidebar.vue

修复了 #XYZ
丰富一下面板的前端功能
- 新增 `iframe` 链接跳转按钮。
- 拖拽边界检测，通过 `clamp` 函数计算拖拽位置，确保 `iframe` 不会超出页面可视区域。
- 移动端支持拖拽事件，添加了 `touchstart`、`touchmove`、`touchend` 事件，使拖拽在移动设备上也能正常使用。
- 优化移动端 `iframe` 的窗口尺寸。

🎈 perf: 优化了iframe窗口，新增跳转按钮

---

astrbot/core/core_lifecycle.py
astrbot/core/initial_loader.py
astrbot/core/platform/manager.py
astrbot/core/platform/platform.py
astrbot/core/platform/sources/aiocqhttp/aiocqhttp_platform_adapter.py
astrbot/core/platform/sources/dingtalk/dingtalk_adapter.py
astrbot/core/platform/sources/gewechat/client.py
astrbot/core/platform/sources/gewechat/gewechat_platform_adapter.py
astrbot/core/platform/sources/lark/lark_adapter.py
astrbot/core/platform/sources/qqofficial/qqofficial_platform_adapter.py
astrbot/core/platform/sources/qqofficial_webhook/qo_webhook_adapter.py
astrbot/core/platform/sources/qqofficial_webhook/qo_webhook_server.py
astrbot/core/platform/sources/telegram/tg_adapter.py
astrbot/core/platform/sources/webchat/webchat_adapter.py
astrbot/core/platform/sources/wecom/wecom_adapter.py
astrbot/dashboard/__init__.py
astrbot/dashboard/routes/config.py
astrbot/dashboard/routes/stat.py
astrbot/dashboard/routes/update.py
astrbot/dashboard/server.py
dashboard/src/views/PlatformPage.vue
main.py

这个 PR 完善了消息平台的优雅退出的问题，好处是能够直接支持消息平台的热重载，并且 AstrBot 的重启速度更快。

支持所有消息平台的优雅退出

---

astrbot/core/utils/io.py
astrbot/core/utils/t2i/local_strategy.py
astrbot/core/utils/t2i/network_strategy.py
astrbot/core/zip_updator.py
astrbot/dashboard/routes/plugin.py
astrbot/dashboard/routes/stat.py
requirements.txt

已经修复了 #950 
fix: 统一 SSL 证书验证逻辑，修复下载问题，或者版本更新等出现 `Cannot connect to host github.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1020)')]` 的问题
- 在 `astrbot\core\utils\io.py` 、 `astrbot\core\zip_updator.py` 、`astrbot\dashboard\routes\plugin.py` 中，统一使用 certifi 提供的 CA 证书进行 SSL 连接
- 修改 `download_image_by_url`、`download_file`、`fetch_release_info` 等函数，使用 `aiohttp.TCPConnector(ssl=ssl_context)`
- 修复部分因 SSL 证书问题导致的下载失败情况
- 增强错误处理逻辑，确保在 SSL 连接异常时可以自动回退到默认证书策略
- 将 `certifi` 写入 `requirements.txt` 中

fix: fix SSLCertVerificationError

---

astrbot/core/platform/sources/telegram/tg_adapter.py

修复了 #975
updater未关闭
新增updater的关闭逻辑

Improves Telegram adapter termination

---

dashboard/src/views/ExtensionMarketplace.vue

修复了 #927
插件市场过滤条件不一致
过滤条件作为变量提出，卡片筛选过滤字段保持一致

feat: 插件市场列表卡片过滤条件提出变量保持一致

---

.gitignore
astrbot/core/message/components.py
astrbot/core/platform/sources/gewechat/client.py
astrbot/core/platform/sources/gewechat/downloader.py
astrbot/core/platform/sources/gewechat/gewechat_event.py
astrbot/core/platform/sources/gewechat/xml_data_parser.py
requirements.txt

1. 增加gewe的表情包解析、发送功能
2. 对gewe引用消息的解析
3. 对gewe的视频解析，并在发送视频时优先考虑使用视频的cdn xml进行加速发送

添加对gewe的表情包、引用消息、视频的支持

---

astrbot/core/db/__init__.py
astrbot/core/db/sqlite.py
astrbot/dashboard/routes/__init__.py
astrbot/dashboard/routes/conversation.py
astrbot/dashboard/server.py
dashboard/src/layouts/full/vertical-sidebar/NavItem.vue
dashboard/src/layouts/full/vertical-sidebar/sidebarItem.ts
dashboard/src/router/MainRoutes.ts
dashboard/src/scss/layout/_sidebar.scss
dashboard/src/views/ConversationPage.vue

✨ 支持 WebUI 对话管理

---

Dockerfile_with_node
README.md
astrbot/core/__init__.py
astrbot/core/config/default.py
astrbot/core/db/sqlite.py
astrbot/core/db/sqlite_init.sql
astrbot/core/pipeline/process_stage/method/llm_request.py
astrbot/core/star/star_manager.py
astrbot/core/star/updator.py
astrbot/core/zip_updator.py
astrbot/dashboard/routes/auth.py
astrbot/dashboard/routes/conversation.py
astrbot/dashboard/routes/plugin.py
astrbot/dashboard/routes/stat.py
astrbot/dashboard/routes/update.py
changelogs/v3.5.0.md
dashboard/src/layouts/full/vertical-header/VerticalHeader.vue
dashboard/src/views/ExtensionMarketplace.vue
packages/astrbot/main.py
packages/session_controller/main.py
pyproject.toml
uv.lock

部分api获取不到model导致key泄露，使用正则表达式过滤掉key内容
获取不到model导致key泄露。
旧：获取模型列表失败: 405, message='Attempt to decode JSON with unexpected mimetype: text/html', url='https://gemini-proxy.808711.xyz/v1beta/models?key=***'
修改后：获取模型列表失败: 405, message='Attempt to decode JSON with unexpected mimetype: text/html', url='https://gemini-proxy.808711.xyz/v1beta/models?key=防止key被盗用已隐藏'
使用正则表达式替换key为防止key被盗用已隐藏

部分api获取不到model导致key泄露，使用正则表达式过滤掉key内容

---

astrbot/core/platform/sources/gewechat/client.py

我当前正在开发的插件功能需要获取用户通讯录列表。
由于现有client未提供通讯录接口的实现，因此自行开发。

feat: gewechat client增加获取通讯录列表接口

---

Dockerfile

修复了 #979 
通过 pyffmpeg 来释出 ffmpeg 文件。（因为同时也需要安装 pyffmpeg 库）

✨docker 镜像提供内置 ffmpeg

---

astrbot/core/provider/sources/gemini_source.py
astrbot/core/provider/sources/openai_source.py

OpenAI source 也支持 API Key 的负载均衡请求（暂时使用随机负载均衡）

🎈 perf: OpenAI sources supports api key load balance(random)

---

astrbot/core/platform/sources/aiocqhttp/aiocqhttp_message_event.py

修复 aiocqhttp 适配器下空白 plain 导致的报错

---

astrbot/dashboard/routes/log.py
dashboard/src/components/shared/ConsoleDisplayer.vue
dashboard/src/layouts/full/vertical-header/VerticalHeader.vue
dashboard/src/stores/common.js

1. SSE 比 WebSockets 性能更好
2. 解决反代需要复杂配置的问题，参考 #544

🏗 refactor: log 通信使用 SSE 替代 Websockets

---

astrbot/core/config/default.py
astrbot/core/provider/manager.py
astrbot/core/provider/sources/dashscope_tts.py

> 以下内容可以新版本上线后粘贴到文档中。
前往 [阿里云百炼控制台](https://bailian.console.aliyun.com/#/home)，点击右上角 API_KEY
右上角按钮申请开通模型服务。
开通好后，前往模型市场，寻找自己想要的语音合成模型：
进入 AstrBot，新建 阿里云百炼_TTS 提供商，输入相关配置：
- model: 模型名，在这里获得：
- ![image](https://github.com/user-attachments/assets/586a8816-c00f-4da0-89ef-8f936a4a190c)
- voice: 音色，在这里获得:
- ![image](https://github.com/user-attachments/assets/15788be1-6a6a-4f77-a4a5-f5c6ef350a9f)

✨feat: 支持阿里云百炼 TTS

---

astrbot/core/platform/sources/telegram/tg_event.py
pyproject.toml
requirements.txt
uv.lock

✨ feat: 支持 Telegram MarkdownV2 渲染

---

astrbot/core/config/default.py
astrbot/core/db/plugin/sqlite_impl.py
astrbot/core/pipeline/process_stage/method/llm_request.py
astrbot/core/pipeline/result_decorate/stage.py
astrbot/core/provider/sources/edge_tts_source.py
astrbot/core/provider/sources/gemini_source.py
astrbot/dashboard/routes/static_file.py
packages/session_controller/main.py

增加对Gemini系列模型safetySettings参数的支持，以增强模型输出的内容安全性和可控性。通过配置该参数，用户能够根据具体需求调整模型生成内容的安全级别，从而更好地满足不同应用场景下的合规性和用户体验要求。https://github.com/AstrBotDevs/AstrBot/issues/216#issuecomment-2506458289
在编辑模型设置时提供安全过滤器设置选项。默认过滤器级别设置为BLOCK_MEDIUM_AND_ABOVE(中等及以上风险时过滤)
[Gemini API文档中对于safetySettings参数的支持](https://ai.google.dev/gemini-api/docs/safety-settings?hl=zh-cn)

feature:增加对Gemini系列模型的安全设置参数支持

---

astrbot/core/log.py
astrbot/dashboard/routes/log.py
dashboard/src/components/shared/ConsoleDisplayer.vue
dashboard/src/stores/common.js
dashboard/src/views/ConsolePage.vue

✨ feat: 更新日志发布机制，支持日志级别和内容的字典格式，增加日志筛选功能

---

astrbot/core/platform/sources/wecom/wecom_event.py
astrbot/core/provider/sources/dashscope_tts.py

fix: 修复阿里云百炼 TTS 只能发送一次语音，第二次就会报错 

---

astrbot/core/config/default.py
astrbot/core/provider/manager.py
astrbot/core/provider/sources/minimax_tts_api_source.py
dashboard/src/components/shared/AstrBotConfig.vue
dashboard/src/views/ProviderPage.vue

[MiniMax](https://www.minimaxi.com/platform_overview)具有业界领先的TTS模型以及API服务. AstrBot未对MiniMax TTS进行支持, 属实可惜.
故在此PR中添加了对MiniMax TTS API的支持.
1. 新增`astrbot/core/provider/sources/minimax_tts_api_source.py`, 定义了类`ProviderMiniMaxTTSAPI`并实现了相关逻辑.
2. 修改`astrbot/core/config/default.py`, 添加了MiniMax TTS相关的配置参数与解释信息.
3. 修改`astrbot/core/provider/manager.py`, 添加`minimax_tts_api` case分支.
4. 修改`dashboard/src/views/ProviderPage.vue`, 添加MiniMax Logo矢量图地址.
MiniMax TTS API 支持请求混合音色(`timber_weights`), 本人实测混合音色生成的语音质量较高. 但是混合音色的请求参数复杂, 需构建`List[Dict[str, Union[str, int]]]`类型对象, 现有的Provider配置窗口疑似无法做到直接使用带约束的前端输入来配置此类复杂对象, 故目前采用输入json字符串进行配置, 在Adapter中对字符串进行反序列化获得目标对象. 这需要用户熟悉json字符串的编写, 以及查阅MiniMax给出的预览代码, 有些麻烦. 希望未来可以扩展配置窗口的约束能力或者讨论出更加合理的配置方式.

Feature: 添加对 MiniMax TTS API的支持

---

astrbot/core/provider/sources/dify_source.py

Feature: supports dify user param

---

dashboard/src/theme/DarkTheme.ts
dashboard/src/theme/LightTheme.ts
dashboard/src/types/themeTypes/ThemeType.ts
dashboard/src/views/ChatPage.vue

Improve: WebUI ChatPage markdown code block background
